import { TextRank } from './TextRank.js';

export class KeywordDescriptor {
    keywords;

    constructor(text) {
        const words = this.getWords(text);
        const rank = this.getRank(words);

        // Execute TextRank and sort results
        this.keywords = [...rank.execute().entries()]
            .sort((a, b) => b[1] - a[1])
            .map(([word]) => word);
    }

    getWords(text) {
        const cleanedText = removeHTMLTags(text)
            .toLowerCase()
            .replace(/[^a-z\s]/g, ' ');

        return cleanedText
            .split(/\s+/)
            .filter(w => w.length > 2 && !KeywordDescriptor.invalidWords.has(w));
    }

    getRank(words) {
        const rank = new TextRank();
        const windowSize = 3;

        for (let i = 0; i < words.length; i++) {
            const from = words[i];
            const context = words.slice(
                Math.max(0, i - windowSize),
                Math.min(words.length, i + windowSize + 1)
            );

            for (const to of context) {
                if (from !== to) {
                    rank.addEdge(from, to);
                }
            }
        }

        return rank;
    }

    static invalidWords = new Set([
        "aboard",
        "about",
        "above",
        "absent",
        "absolutely",
        "across",
        "actually",
        "after",
        "again",
        "against",
        "ago",
        "ahead",
        "all",
        "almost",
        "alone",
        "along",
        "alongside",
        "already",
        "also",
        "always",
        "amid",
        "amidst",
        "among",
        "amongst",
        "and",
        "another",
        "any",
        "anybody",
        "anyone",
        "anything",
        "are",
        "around",
        "as",
        "astride",
        "at",
        "atop",
        "available",
        "away",
        "back",
        "bar",
        "before",
        "behind",
        "below",
        "beneath",
        "beside",
        "besides",
        "best",
        "better",
        "between",
        "beyond",
        "both",
        "but",
        "by",
        "can",
        "cant",
        "car",
        "cars",
        "certainly",
        "circa",
        "clearly",
        "close",
        "come",
        "despite",
        "did",
        "didnt",
        "directly",
        "does",
        "doesnt",
        "down",
        "during",
        "each",
        "early",
        "eight",
        "either",
        "eleven",
        "else",
        "enough",
        "especially",
        "even",
        "eventually",
        "ever",
        "everybody",
        "everyone",
        "everything",
        "exactly",
        "except",
        "far",
        "fast",
        "few",
        "finally",
        "five",
        "for",
        "forward",
        "four",
        "from",
        "get",
        "got",
        "hard",
        "has",
        "have",
        "he",
        "her",
        "here",
        "hers",
        "herself",
        "him",
        "himself",
        "his",
        "home",
        "how",
        "however",
        "I",
        "in",
        "indeed",
        "inside",
        "instead",
        "into",
        "it",
        "its",
        "itself",
        "just",
        "keep",
        "later",
        "least",
        "less",
        "lets",
        "like",
        "little",
        "long",
        "many",
        "maybe",
        "me",
        "mine",
        "minus",
        "more",
        "most",
        "much",
        "must",
        "my",
        "myself",
        "near",
        "nearly",
        "necessary",
        "need",
        "neither",
        "never",
        "nine",
        "no",
        "nobody",
        "none",
        "noone",
        "nor",
        "not",
        "nothing",
        "notwithstanding",
        "now",
        "of",
        "off",
        "often",
        "ok",
        "on",
        "once",
        "one",
        "only",
        "onto",
        "opposite",
        "or",
        "other",
        "others",
        "our",
        "ours",
        "ourselves",
        "out",
        "outside",
        "over",
        "particularly",
        "past",
        "per",
        "perhaps",
        "please",
        "plus",
        "post ",
        "pre ",
        "pretty",
        "pro ",
        "probably",
        "put",
        "puts",
        "quickly",
        "quite",
        "rather",
        "re",
        "really",
        "recently",
        "refer",
        "refers",
        "right",
        "sans",
        "save",
        "seven",
        "several",
        "she",
        "short",
        "simply",
        "since",
        "six",
        "so",
        "some",
        "somebody",
        "someone",
        "something",
        "sometimes",
        "soon",
        "still",
        "such",
        "suddenly",
        "system",
        "take",
        "ten",
        "tell",
        "tells",
        "than",
        "that",
        "the",
        "thee",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "there",
        "therefore",
        "these",
        "they",
        "thine",
        "this",
        "those",
        "thou",
        "three",
        "through",
        "throughout",
        "thus",
        "thy",
        "till",
        "to",
        "today",
        "together",
        "tonight",
        "too",
        "toward",
        "towards",
        "twelve",
        "two",
        "under",
        "underneath",
        "unlike",
        "unnecessary",
        "until",
        "unto",
        "up",
        "upon",
        "upside",
        "us",
        "use",
        "usually",
        "vehicle",
        "versus",
        "very",
        "via",
        "vice",
        "volkswagen",
        "was",
        "we",
        "website",
        "well",
        "what",
        "whatever",
        "when",
        "where",
        "which",
        "whichever",
        "who",
        "whoever",
        "whom",
        "whomever",
        "whose",
        "why",
        "will",
        "with",
        "within",
        "without",
        "wont",
        "worth",
        "yet",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "zero"
    ]);
}

export function removeHTMLTags(input) {
    return input.includes('<') ? input.replace(/<[^>]*>/g, '') : input;
}

export default KeywordDescriptor;